import type { Locale } from '@/i18n/locales';

export interface ProductDetailStrings {
  selectSpec: string;
  selectQuantity: string;
  requestQuote: string;
  requestCoa: string;
  moqPrefix: string;
  customization: string;
  detail: string;
  specifications: string;
  description: string;
  plantingBase: string;
  plantingBaseDesc: string;
  packaging: string;
  packagingDesc: string;
  certifications: string;
  certificationsDesc: string;
  interestedIn: string;
  ctaBody: string;
  contactPage: string;
  specsToBeDiscussed: string;
}

export const productDetailStrings: Record<Locale, ProductDetailStrings> = {
  en: {
    selectSpec: 'Select Specification (multi-select):',
    selectQuantity: 'Select Order Quantity (multi-select):',
    requestQuote: 'Request Quote',
    requestCoa: 'Request COA / SDS',
    moqPrefix: 'MOQ:',
    customization: 'Customization available',
    detail: 'Detail',
    specifications: 'Product Specifications',
    description: 'Product Description',
    plantingBase: 'Our Planting Base',
    plantingBaseDesc: 'Yunma-13 industrial hemp cultivation in Chuxiong, Yunnan Province',
    packaging: 'Packaging & Shipment',
    packagingDesc: 'Export-ready: PE inner + aluminum foil bags (5 kg each), carton packing',
    certifications: 'Our Certifications',
    certificationsDesc: 'Licensed industrial hemp processor with FDA registration',
    interestedIn: 'Interested in',
    ctaBody: 'Get a quotation or technical documentation. Our team responds within 24 hours.',
    contactPage: 'Contact Page',
    specsToBeDiscussed: 'specifications to be discussed',
  },
  de: {
    selectSpec: 'Spezifikation auswählen (Mehrfachauswahl):',
    selectQuantity: 'Bestellmenge auswählen (Mehrfachauswahl):',
    requestQuote: 'Angebot anfordern',
    requestCoa: 'COA / SDS anfordern',
    moqPrefix: 'MOQ:',
    customization: 'Individualisierung verfügbar',
    detail: 'Details',
    specifications: 'Produktspezifikationen',
    description: 'Produktbeschreibung',
    plantingBase: 'Unsere Anbaubasis',
    plantingBaseDesc: 'Yunma-13 Industriehanfanbau in Chuxiong, Provinz Yunnan',
    packaging: 'Verpackung & Versand',
    packagingDesc: 'Exportfertig: PE-Innenbeutel + Aluminiumfolienbeutel (5 kg), Kartonverpackung',
    certifications: 'Unsere Zertifizierungen',
    certificationsDesc: 'Lizenzierter Industriehanfverarbeiter mit FDA-Registrierung',
    interestedIn: 'Interesse an',
    ctaBody: 'Erhalten Sie ein Angebot oder technische Dokumentation. Unser Team antwortet innerhalb von 24 Stunden.',
    contactPage: 'Kontaktseite',
    specsToBeDiscussed: 'Spezifikationen nach Absprache',
  },
  fr: {
    selectSpec: "Sélectionner la spécification (multi-sélection) :",
    selectQuantity: "Sélectionner la quantité (multi-sélection) :",
    requestQuote: 'Demander un devis',
    requestCoa: 'Demander COA / SDS',
    moqPrefix: 'MOQ :',
    customization: 'Personnalisation disponible',
    detail: 'Détails',
    specifications: 'Spécifications du produit',
    description: 'Description du produit',
    plantingBase: 'Notre base de culture',
    plantingBaseDesc: "Culture de chanvre industriel Yunma-13 à Chuxiong, province du Yunnan",
    packaging: "Emballage & Expédition",
    packagingDesc: "Prêt à l'export : sachets PE + aluminium (5 kg chacun), emballage carton",
    certifications: 'Nos certifications',
    certificationsDesc: "Transformateur de chanvre industriel agréé avec enregistrement FDA",
    interestedIn: 'Intéressé par',
    ctaBody: "Obtenez un devis ou une documentation technique. Notre équipe répond sous 24 heures.",
    contactPage: 'Page de contact',
    specsToBeDiscussed: 'spécifications à discuter',
  },
  es: {
    selectSpec: 'Seleccionar especificación (selección múltiple):',
    selectQuantity: 'Seleccionar cantidad (selección múltiple):',
    requestQuote: 'Solicitar cotización',
    requestCoa: 'Solicitar COA / SDS',
    moqPrefix: 'MOQ:',
    customization: 'Personalización disponible',
    detail: 'Detalles',
    specifications: 'Especificaciones del producto',
    description: 'Descripción del producto',
    plantingBase: 'Nuestra base de cultivo',
    plantingBaseDesc: 'Cultivo de cáñamo industrial Yunma-13 en Chuxiong, provincia de Yunnan',
    packaging: 'Embalaje y envío',
    packagingDesc: 'Listo para exportación: bolsas PE + aluminio (5 kg c/u), embalaje en cartón',
    certifications: 'Nuestras certificaciones',
    certificationsDesc: 'Procesador de cáñamo industrial con licencia y registro FDA',
    interestedIn: 'Interesado en',
    ctaBody: 'Obtenga una cotización o documentación técnica. Nuestro equipo responde en 24 horas.',
    contactPage: 'Página de contacto',
    specsToBeDiscussed: 'especificaciones a discutir',
  },
  it: {
    selectSpec: 'Seleziona specifica (selezione multipla):',
    selectQuantity: "Seleziona quantità dell'ordine (selezione multipla):",
    requestQuote: 'Richiedi preventivo',
    requestCoa: 'Richiedi COA / SDS',
    moqPrefix: 'MOQ:',
    customization: 'Personalizzazione disponibile',
    detail: 'Dettagli',
    specifications: 'Specifiche del prodotto',
    description: 'Descrizione del prodotto',
    plantingBase: 'La nostra base di coltivazione',
    plantingBaseDesc: 'Coltivazione di canapa industriale Yunma-13 a Chuxiong, provincia dello Yunnan',
    packaging: 'Imballaggio e spedizione',
    packagingDesc: "Pronto per l'export: sacchetti PE + alluminio (5 kg ciascuno), imballaggio in cartone",
    certifications: 'Le nostre certificazioni',
    certificationsDesc: 'Trasformatore di canapa industriale autorizzato con registrazione FDA',
    interestedIn: 'Interessato a',
    ctaBody: 'Ottieni un preventivo o documentazione tecnica. Il nostro team risponde entro 24 ore.',
    contactPage: 'Pagina contatti',
    specsToBeDiscussed: 'specifiche da concordare',
  },
  pt: {
    selectSpec: 'Selecionar especificação (seleção múltipla):',
    selectQuantity: 'Selecionar quantidade (seleção múltipla):',
    requestQuote: 'Solicitar cotação',
    requestCoa: 'Solicitar COA / SDS',
    moqPrefix: 'MOQ:',
    customization: 'Personalização disponível',
    detail: 'Detalhes',
    specifications: 'Especificações do produto',
    description: 'Descrição do produto',
    plantingBase: 'Nossa base de cultivo',
    plantingBaseDesc: 'Cultivo de cânhamo industrial Yunma-13 em Chuxiong, província de Yunnan',
    packaging: 'Embalagem e envio',
    packagingDesc: 'Pronto para exportação: sacos PE + alumínio (5 kg cada), embalagem em caixa',
    certifications: 'Nossas certificações',
    certificationsDesc: 'Processador de cânhamo industrial licenciado com registro FDA',
    interestedIn: 'Interessado em',
    ctaBody: 'Obtenha uma cotação ou documentação técnica. Nossa equipe responde em 24 horas.',
    contactPage: 'Página de contato',
    specsToBeDiscussed: 'especificações a discutir',
  },
  ja: {
    selectSpec: '仕様を選択（複数選択可）：',
    selectQuantity: '注文数量を選択（複数選択可）：',
    requestQuote: '見積もりを依頼',
    requestCoa: 'COA / SDS を依頼',
    moqPrefix: 'MOQ：',
    customization: 'カスタマイズ対応可能',
    detail: '詳細',
    specifications: '製品仕様',
    description: '製品説明',
    plantingBase: '栽培基地',
    plantingBaseDesc: '雲南省楚雄市 Yunma-13 産業用大麻栽培',
    packaging: '包装・出荷',
    packagingDesc: '輸出対応：PE内袋＋アルミ箔袋（各5 kg）、段ボール梱包',
    certifications: '認証資格',
    certificationsDesc: 'FDA登録済み認定産業用大麻加工事業者',
    interestedIn: 'ご興味のある製品：',
    ctaBody: 'お見積もりや技術資料をご提供いたします。24時間以内にご返答いたします。',
    contactPage: 'お問い合わせページ',
    specsToBeDiscussed: '仕様は要相談',
  },
  fi: {
    selectSpec: 'Valitse spesifikaatio (monivalinta):',
    selectQuantity: 'Valitse tilausmäärä (monivalinta):',
    requestQuote: 'Pyydä tarjous',
    requestCoa: 'Pyydä COA / SDS',
    moqPrefix: 'MOQ:',
    customization: 'Räätälöinti saatavilla',
    detail: 'Tiedot',
    specifications: 'Tuotespesifikaatiot',
    description: 'Tuotekuvaus',
    plantingBase: 'Viljelyalueemme',
    plantingBaseDesc: 'Yunma-13 teollisen hampun viljely Chuxiongissa, Yunnanin maakunnassa',
    packaging: 'Pakkaus ja toimitus',
    packagingDesc: 'Vientivalmis: PE-sisäpussi + alumiinifolio (5 kg/pussi), pahvilaatikkopakkaus',
    certifications: 'Sertifikaattimme',
    certificationsDesc: 'Lisensoitu teollisen hampun jalostaja FDA-rekisteröinnillä',
    interestedIn: 'Kiinnostaako',
    ctaBody: 'Pyydä tarjous tai tekninen dokumentaatio. Tiimimme vastaa 24 tunnin sisällä.',
    contactPage: 'Yhteydenottolomake',
    specsToBeDiscussed: 'spesifikaatiot sovittavissa',
  },
};
